

var state = {
    i : 0,
    j:0,
    k:0,
    l:0,
};

function nexthat()
{
    console.log("inside function nexthat");
    console.log(state.i);
    var dress=document.getElementById("hat");
    if(state.i===0){
    dress.setAttribute("class","hat1");
        state.i++;
        console.log(state.i);
    }
    else
     if(state.i===1){
    dress.setAttribute("class","hat2");
         state.i++;
         console.log(state.i);
    }
    else
    if(state.i===2){
   dress.setAttribute("class","hat3");
        state.i++;
        console.log(state.i);
   }
    else
    if(state.i===3){
    dress.setAttribute("class","hat4");
        state.i++;
        console.log(state.i);
    }
    else
    if(state.i===4){
    dress.setAttribute("class","hat5");
        state.i++;
        console.log(state.i);
    }
     else
     if(state.i===5){
    dress.setAttribute("class","hat6");
         state.i++;
         console.log(state.i);
    }
    else
     if(state.i===6){
    dress.setAttribute("class","hat7");
         state.i++;
         console.log(state.i);
    }
    else
    if(state.i===7){
   dress.setAttribute("class","hat8");
        state.i++;
        console.log(state.i);
   }
    else
    if(state.i===8){
    dress.setAttribute("class","hat9");
        state.i++;
        console.log(state.i);
    }
    else
    if(state.i===9){
    dress.setAttribute("class","hat10");
        state.i++;
        console.log(state.i);
    }
     else
     if(state.i===10){
    dress.setAttribute("class","hat11");
         state.i++;
         console.log(state.i);
    }
    else
    if(state.i===11){
   dress.setAttribute("class","hat12");
        state.i++;
        console.log(state.i);
   }
   else
    if(state.i===12){
   dress.setAttribute("class","hat13");
        state.i++;
        console.log(state.i);
   }
   else
   if(state.i===13){
  dress.setAttribute("class","hat14");
       state.i++;
       console.log(state.i);
  }
   else
   if(state.i===14){
   dress.setAttribute("class","hat15");
       state.i++;
       console.log(state.i);
   }
   else
   if(state.i===15){
   dress.setAttribute("class","hat16");
       state.i=0;
   }
}

function nextoutfit()
{
    console.log("inside function nextoutfit");
    console.log(state.j);
    var shoe=document.getElementById("outfit");
    if(state.j===0){
    shoe.setAttribute("class","outfit1");
        state.j++;
        console.log(state.j);
    }
    else
     if(state.j===1){
    shoe.setAttribute("class","outfit2");
         state.j++;
         console.log(state.j);
    }
    else
     if(state.j===2){
    shoe.setAttribute("class","outfit3");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===3){
    shoe.setAttribute("class","outfit4");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===4){
    shoe.setAttribute("class","outfit5");
          state.j++;
         console.log(state.j);
    }
    else
    if(state.j===5){
    shoe.setAttribute("class","outfit6");
          state.j++;
         console.log(state.j);
    }
    else
    if(state.j===6){
    shoe.setAttribute("class","outfit7");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===7){
    shoe.setAttribute("class","outfit8");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===8){
    shoe.setAttribute("class","outfit9");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===9){
    shoe.setAttribute("class","outfit10");
         state.j++;
         console.log(state.j);
    }
    else
     if(state.j===10){
    shoe.setAttribute("class","outfit11");
         state.j++;
         console.log(state.j);
    }
    else
     if(state.j===11){
    shoe.setAttribute("class","outfit12");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===12){
    shoe.setAttribute("class","outfit13");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===13){
    shoe.setAttribute("class","outfit14");
          state.j++;
         console.log(state.j);
    }
    else
    if(state.j===14){
    shoe.setAttribute("class","outfit15");
          state.j++;
         console.log(state.j);
    }
    else
    if(state.j===15){
    shoe.setAttribute("class","outfit16");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===16){
    shoe.setAttribute("class","outfit17");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===17){
    shoe.setAttribute("class","outfit18");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===18){
    shoe.setAttribute("class","outfit19");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===19){
   shoe.setAttribute("class","outfit20");
        state.j++;
        console.log(state.j);
   }
   else
    if(state.j===20){
   shoe.setAttribute("class","outfit21");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===21){
   shoe.setAttribute("class","outfit22");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===22){
   shoe.setAttribute("class","outfit23");
         state.j++;
        console.log(state.j);
   }
   else
   if(state.j===23){
   shoe.setAttribute("class","outfit24");
         state.j++;
        console.log(state.j);
   }
   else
   if(state.j===24){
   shoe.setAttribute("class","outfit25");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===25){
   shoe.setAttribute("class","outfit26");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===26){
   shoe.setAttribute("class","outfit27");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===27){
   shoe.setAttribute("class","outfit28");
        state.j++;
        console.log(state.j);
   }
   else
    if(state.j===28){
   shoe.setAttribute("class","outfit29");
        state.j++;
        console.log(state.j);
   }
   else
    if(state.j===29){
   shoe.setAttribute("class","outfit30");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===30){
   shoe.setAttribute("class","outfit31");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===31){
   shoe.setAttribute("class","outfit32");
         state.j++;
        console.log(state.j);
   }
   else
   if(state.j===32){
   shoe.setAttribute("class","outfit33");
         state.j++;
        console.log(state.j);
   }
   else
   if(state.j===33){
   shoe.setAttribute("class","outfit34");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===34){
   shoe.setAttribute("class","outfit35");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===35){
   shoe.setAttribute("class","outfit36");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===36){
   shoe.setAttribute("class","outfit37");
        state.j++;
        console.log(state.j);
   }
    else
     if(state.j===37){
    shoe.setAttribute("class","outfit38");
         state.j++;
         console.log(state.j);
    }
    else
     if(state.j===39){
    shoe.setAttribute("class","outfit40");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===40){
    shoe.setAttribute("class","outfit41");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===41){
    shoe.setAttribute("class","outfit42");
          state.j++;
         console.log(state.j);
    }
    else
    if(state.j===42){
    shoe.setAttribute("class","outfit43");
          state.j++;
         console.log(state.j);
    }
    else
    if(state.j===43){
    shoe.setAttribute("class","outfit44");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===44){
    shoe.setAttribute("class","outfit45");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===45){
    shoe.setAttribute("class","outfit46");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===46){
    shoe.setAttribute("class","outfit47");
         state.j++;
         console.log(state.j);
    }
    else
     if(state.j===47){
    shoe.setAttribute("class","outfit48");
         state.j++;
         console.log(state.j);
    }
    else
     if(state.j===48){
    shoe.setAttribute("class","outfit49");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===49){
    shoe.setAttribute("class","outfit50");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===50){
    shoe.setAttribute("class","outfit51");
          state.j++;
         console.log(state.j);
    }
    else
    if(state.j===51){
    shoe.setAttribute("class","outfit52");
          state.j++;
         console.log(state.j);
    }
    else
    if(state.j===52){
    shoe.setAttribute("class","outfit53");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===53){
    shoe.setAttribute("class","outfit54");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===54){
    shoe.setAttribute("class","outfit55");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===55){
    shoe.setAttribute("class","outfit56");
         state.j++;
         console.log(state.j);
    }
    else
    if(state.j===56){
   shoe.setAttribute("class","outfit57");
        state.j++;
        console.log(state.j);
   }
   else
    if(state.j===57){
   shoe.setAttribute("class","outfit58");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===58){
   shoe.setAttribute("class","outfit59");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===59){
   shoe.setAttribute("class","outfit60");
         state.j++;
        console.log(state.j);
   }
   else
   if(state.j===60){
   shoe.setAttribute("class","outfit61");
         state.j++;
        console.log(state.j);
   }
   else
   if(state.j===61){
   shoe.setAttribute("class","outfit62");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===62){
   shoe.setAttribute("class","outfit63");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===63){
   shoe.setAttribute("class","outfit64");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===64){
   shoe.setAttribute("class","outfit65");
        state.j++;
        console.log(state.j);
   }
   else
    if(state.j===65){
   shoe.setAttribute("class","outfit66");
        state.j++;
        console.log(state.j);
   }
   else
    if(state.j===66){
   shoe.setAttribute("class","outfit67");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===67){
   shoe.setAttribute("class","outfit68");
        state.j++;
        console.log(state.j);
   }
   else
   if(state.j===68){
   shoe.setAttribute("class","outfit69");
         state.j=0;
   }
}

function nextaccessory()
{
    console.log("inside function nextaccessory");
    console.log(state.k);
    var shoe=document.getElementById("accessory");
    if(state.k===0){
    shoe.setAttribute("class","accessory1");
        state.k++;
        console.log(state.k);
    }
    else
    if(state.k===1){
    shoe.setAttribute("class","accessory2");
        state.k++;
        console.log(state.k);
        }   
    else
    if(state.k===2){
        shoe.setAttribute("class","accessory3");
        state.k++;
        console.log(state.k);
          }   
    else
    if(state.k===3){
        shoe.setAttribute("class","accessory4");
        state.k++;
        console.log(state.k);
          } 
    else
    if(state.k===4){
        shoe.setAttribute("class","accessory5");
        state.k++;
        console.log(state.k);
        }   
    else
    if(state.k===5){
        shoe.setAttribute("class","accessory6");
        state.k++;
        console.log(state.k);
          }   
    else
    if(state.k===6){
        shoe.setAttribute("class","accessory7");
        state.k++;
        console.log(state.k);
          } 
    else
    if(state.k===7){
        shoe.setAttribute("class","accessory8");
        state.k++;
        console.log(state.k);
        }   
    else
    if(state.k===8){
        shoe.setAttribute("class","accessory9");
        state.k++;
        console.log(state.k);
          }   
    else
    if(state.k===9){
        shoe.setAttribute("class","accessory10");
        state.k++;
        console.log(state.k);
          } 
    else
    if(state.k===10){
        shoe.setAttribute("class","accessory11");
        state.k++;
        console.log(state.k);
        }   
    else
    if(state.k===11){
        shoe.setAttribute("class","accessory12");
        state.k++;
        console.log(state.k);
          }   
    else
    if(state.k===13){
        shoe.setAttribute("class","accessory13");
        state.k++;
        console.log(state.k);
          } 
    else
    if(state.k===14){
        shoe.setAttribute("class","accessory14");
        state.k++;
        console.log(state.k);
        }   
    else
    if(state.k===15){
        shoe.setAttribute("class","accessory15");
        state.k++;
        console.log(state.k);
          }   
    else
    if(state.k===16){
        shoe.setAttribute("class","accessory17");
        state.k++;
        console.log(state.k);
          } 
    else
    if(state.k===17){
        shoe.setAttribute("class","accessory18");
        state.k++;
        console.log(state.k);
        }   
    else
    if(state.k===18){
        shoe.setAttribute("class","accessory19");
        state.k++;
        console.log(state.k);
          }   
    else
    if(state.k===19){
        shoe.setAttribute("class","accessory20");
        state.k++;
        console.log(state.k);
          } 
    else
    if(state.k===20){
        shoe.setAttribute("class","accessory21");
        state.k++;
        console.log(state.k);
        }   
    else
    if(state.k===21){
        shoe.setAttribute("class","accessory22");
        state.k=0;
          }   
    
}

function nextshoe()
{
    console.log("inside function nextshoe");
    console.log(state.l);
    var shoe=document.getElementById("shoe");
    if(state.l===0){
    shoe.setAttribute("class","shoes1");
        state.l++;
        console.log(state.l);
    }
    else
    if(state.l===1){
        shoe.setAttribute("class","shoes2");
            state.l++;
            console.log(state.l);
      } 
    else
    if(state.l===2){
        shoe.setAttribute("class","shoes3");
            state.l++;
            console.log(state.l);
        } 
    if(state.l===3){
    shoe.setAttribute("class","shoes4");
        state.l++;
        console.log(state.l);
    }
    else
    if(state.l===4){
        shoe.setAttribute("class","shoes5");
            state.l++;
            console.log(state.l);
      } 
    else
    if(state.l===5){
        shoe.setAttribute("class","shoes6");
            state.l++;
            console.log(state.l);
        } 
    else
    if(state.l===6){
        shoe.setAttribute("class","shoes7");
            state.l++;
            console.log(state.l);
      } 
    else
    if(state.l===7){
        shoe.setAttribute("class","shoes8");
            state.l++;
            console.log(state.l);
        } 
    if(state.l===8){
    shoe.setAttribute("class","shoes9");
        state.l++;
        console.log(state.l);
    }
    else
    if(state.l===9){
        shoe.setAttribute("class","shoes10");
            state.l++;
            console.log(state.l);
      } 
    else
    if(state.l===10){
        shoe.setAttribute("class","shoes11");
            state.l=0;
        } 
}  

